eureka:
  instance:
    hostname: localhost # Ensure the hostname is localhost
    prefer-ip-address: false # Ensure Eureka registers the service with localhost, not the machine's IP
  client:
    fetch-registry: true  # Fetch registry from the Eureka server
    register-with-eureka: true  # Register this service with the Eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka # Correct endpoint to communicate with Eureka server
